SELECT  * FROM Capycom.dbo.CPCM_POSTS
LEFT JOIN Capycom.dbo.CPCM_IMAGES ON Capycom.dbo.CPCM_POSTS.CPCM_PostID = Capycom.dbo.CPCM_IMAGES.CPCM_PostID
WHERE(CPCM_UserID IN (N'FBF90D60-95E5-4E0B-B05B-0F8F12F7F8CE')) AND (CPCM_PostPublishedDate < GETUTCDATE())
ORDER BY  Capycom.dbo.CPCM_POSTS.CPCM_PostPublishedDate  DESC
